#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 11 14:28:57 2021

@author: Marieke_Wesselkamp
"""

import pandas as pd
import utils

#%% Load observations
def load_data():
    
    X = pd.read_csv(r"data/soro_clim", sep=";")
    Y = pd.read_csv(r"data/soro_gpp", sep=";")
    Y_Preles = pd.read_csv(r"data/soro_preles_gpp", sep=";")
    
    # Remove nows with na values
    rows_with_nan = pd.isnull(X).any(1).to_numpy().nonzero()[0]
    X = X.drop(rows_with_nan)
    Y = Y.drop(rows_with_nan)
    
    Y_Preles = Y_Preles.drop(rows_with_nan)
    Y_Preles = Y_Preles.drop(columns=["ET", "SW"])
    
    return X, Y, Y_Preles

#%% Process 
def modify_data(X):
    
    X["date"] = X["date"].str[:4].astype(int) # get years as integers
    X["DOY_sin"], X["DOY_cos"] = utils.encode_doy(X["DOY"]) # encode day of year as sinus and cosinus
        
    return X

#%%
def split_data(X, Y, years):
    
    try:
        row_ind = X["date"].isin(years)
        #print(f"Returns valid years from {years} in \n", X["date"].unique())
        X, Y = X[row_ind], Y[row_ind]
    except: 
        print("Years specification invalid. Returns all years.")

#%%
def subset_data(X, colnames):
    
    try:
        X = X[colnames]
    except:
        print("Columns are missing!")
        
    